
//Types should be in const to avoid typos and duplication since it's a string and could be easily miss spelled
export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCT_BEGIN = 'UPDATE_PRODUCT_BEGIN';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const ADD_SHIPPING = 'ADD_SHIPPING';
export const ADD_USERNAMEINFO = 'ADD_USERNAMEINFO';
export const ADD_PASSWORDINFO = 'ADD_PASSWORDINFO';
export const ADD_TOKEN_ID_INFO = 'ADD_TOKEN_ID_INFO';
export const ADD_USER_DETAIL_INFO = 'ADD_USER_DETAIL_INFO';
export const ADD_PAYMENT_INFO = 'ADD_PAYMENT_INFO';
export const ADD_DELIVERY_INFO = 'ADD_DELIVERY_INFO';
export const ADD_NOTIFICATION_INFO = 'ADD_NOTIFICATION_INFO';
export const ADD_ORDER_INFO = 'ADD_ORDER_INFO';
export const AUTHENTICATING_USER = 'AUTHENTICATION_USER';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
